### ISSUE TITLE
Support directives including shorthand notation

### ISSUE THREAD

**Issue by tomblachut** [tomblachut/svelte-intellij#11]
Related to #2

Not-shorthand `let` is kinda handled since 2019, there needs to be a proper support for all directives, with navigation to definition and value completions. Type checking would be also nice, but it will come later.

This is talking so long because shorthand syntax is pretty novel in terms of language support.

### TODO:
- [x] learn about stubs & indices
- [x] explore solutions to insert JS semantics into attribute name
- [x] analyse how directives interact with each other and rest of the language
- [x] insert JS semantics into attribute name
- [x] provide completions
- [ ] design component model
- [ ] build index of component models
- [ ] wire up `XmlElementDescriptor`s & `XmlAttributeDescriptor`s

**Comment by tomblachut** [comment]
Partially done in #77. Directives no more result in warning highlight

**Comment by tomblachut** [comment]
Will be released as part of 0.16.0

**Comment by tomblachut** [comment]
TODO: provide a matrix of working features for each directive
