### ISSUE TITLE
Expand SvelteResolveTest

### ISSUE THREAD

**Issue by tomblachut** [tomblachut/svelte-intellij#138]
I've created `SvelteResolveTest` in #137 but there's definitely room for adding more cases.

### TODO

- [ ] let directive variables
- [ ] Dollar subscriptions `$store`
- [ ] Reference from component usage to file (go to declaration)
- [ ] Reference from *namespaced* component usage to file (go to declaration)
- [ ] JS file with imported Svelte file: try to import `context="module"` exports

---

FYI Vue plugin is using following helper in some tests:

```kotlin
    private fun doTestResolveLocallyInsideComponent(text: String, expectedPropertyName: String?) {
        myFixture.configureByText("ResolveLocallyInsideComponent.vue", text)
        val reference = myFixture.getReferenceAtCaretPosition()
        TestCase.assertNotNull(reference)
        val target = reference!!.resolve()
        if (expectedPropertyName == null) {
            TestCase.assertNull(target)
        } else {
            val property = if (target is JSImplicitElement) target.parent else target
            TestCase.assertTrue(property is JSProperty)
            TestCase.assertEquals(expectedPropertyName, (property as JSProperty).name)
        }
    }

```
